environment:
  matrix:
    - PYTHON: "C:\\Python26"
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python32"
    - PYTHON: "C:\\Python34"



install:
  - "%PYTHON%/Scripts/pip.exe install flake8 mock nose"
  - "%PYTHON%/Scripts/pip.exe install ."
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

test_script: 
  # - "%PYTHON%/Scripts/nosetests.exe -v"
  # - "%PYTHON%/Scripts/flake8.exe *.py --max-line-length=110"
  - nosetests -v
  - flake8 *.py --max-line-length=110

build: off