# environment:
#   matrix:
#     - PYTHON: "C:\\Python26"
#     - PYTHON: "C:\\Python27"
#     - PYTHON: "C:\\Python32"
#     - PYTHON: "C:\\Python34"

environment:
  PYTHON: "C:\\Python26"

install:
  # - "%PYTHON%\\python.exe -m pip install flake8 mock nose"
  # - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%/Scripts/pip.exe install flake8 mock nose"
  - "%PYTHON%/Scripts/pip.exe install ."

test_script: 
  - "%PYTHON%/Scripts/nosetests.exe -v"
  - "%PYTHON%/Scripts/flake8.exe *.py --max-line-length=110"

build: off