environment:
  matrix:
    - PYTHON: "C:\\Python26"
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python32"
    - PYTHON: "C:\\Python34"

install:
  - pip install flake8 mock nose
  - pip install .
test_script: 
	- nosetests -v && flake8 *.py --max-line-length=110

build: off