# environment:
#   matrix:
#     - PYTHON: "C:\\Python26"
#     - PYTHON: "C:\\Python27"
#     - PYTHON: "C:\\Python32"
#     - PYTHON: "C:\\Python34"

environment:
  PYTHON: "C:\\Python26"

install:
  # - "%PYTHON%\\python.exe -m pip install flake8 mock nose"
  # - "%PYTHON%\\python.exe -m pip install ."
  - ps: Start-FileDownload 'https://bootstrap.pypa.io/get-pip.py'
  - "%PYTHON%\\python.exe get-pip.py"
  - cmd: pip freeze

# test_script: 
# 	- nosetests -v && flake8 *.py --max-line-length=110

build: off